### ISSUE TITLE
✨ FR: VSCode extension

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [Trivadis/plsql-cop-cli#12]
Since there is a plugin for Atom, it would be nice if there would be an extension for VSCode also :D

**Comment by PhilippSalvisberg** [comment]
You probably mean https://atom.io/packages/plsql-linter . It's based on [code](https://github.com/bmazzarol/atom-plsql-linter) that is five years old and it is not maintained by us.

Once it is clear what the SQL Developer team is planning to use as replacement for SQL Developer will consider supporting that IDE. Maybe it's VSCode. However, right now there are no plans to provide a plugin for VScode.
