### ISSUE TITLE
Do not report G-7440 when `in out` is used for `self` as part of a fluent API

### ISSUE THREAD

**Issue by DavidotNet** [Trivadis/plsql-cop-cli#27]
Type OBJECT syntax requires use of IN OUT,  (I think) in this case syntax should not be flagged with 
G-7440: Never use OUT parameters to return values from a function.

create or replace TYPE shape as object
(
    name varchar2(30 char)
  , area number

  , constructor function shape(self in out nocopy shape
                             , in_name varchar2
                             , in_area Number) return self as result
                             
  , member function Updatee(self in out nocopy shape
                         , in_name in varchar2) return boolean
);
/
create or replace type body shape 
as
  constructor function shape (in_name varchar2
                            , in_area number) return self as result is
  begin
    self.name := in_name;
    self.area := in_area;
    return;
  end;
  
  member function Updatee(self in out nocopy shape
                         , in_name in varchar2) return boolean
   is
   begin
      self.name := in_name;
      return true;
   end;
end;

**Comment by PhilippSalvisberg** [comment]
closed with Azure DevOps commit f26d718a87e8bfbf3227a08d4df6dce8610d3740 

(G-7440 is not reported for parameters named "self")
