### ISSUE TITLE
New license 

### ISSUE THREAD

**Issue by camelx1** [Trivadis/plsql-cop-cli#4]
Hi,
How I can get a new license for PL\SQL cop?

**Comment by PhilippSalvisberg** [comment]
Yes, the included trial/preview license of PL/SQL Cop v2.3.1 is expired. v3 which should be released in November 2020 will include a valid trial/preview license again.

Please request a dedicated trial license via https://www.trivadis.com/en/plsql-cop . Either via chat or via the contact information provided in the fact sheet. Thanks.

**Comment by camelx1** [comment]
@PhilippSalvisberg, I can't get a license, no one answers via contact form / chat.
Can you suggest a direct email with whom I could contact?

**Comment by PhilippSalvisberg** [comment]
@camelx1 have you licensed PL/SQL Cop?

**Comment by PhilippSalvisberg** [comment]
BTW. The preview/trial license is valid thru 2021-04-30 [PL/SQL Cop v3.0.0](https://github.com/Trivadis/plsql-cop-cli/releases). 

If you need more. Please leave your contact details here and I'll make sure you will be contacted.

**Comment by camelx1** [comment]
@PhilippSalvisberg, I did not notice that you uploaded new version, I will try 
Thanks you a lot!
