### ISSUE TITLE
File Extensions

### ISSUE THREAD

**Issue by kkhan1008** [Trivadis/plsql-cop-cli#5]
Hi,

is it possible to analyze files with other extensions than the defaults, ie. pkg ?
I tried using the filter argument any which way as shown in the help output (filter="(pks|pkb|pkg)$"), but pkg file are being ignored. 
FYI, pkg files are analyzed when renamed to any default extension.

**Comment by PhilippSalvisberg** [comment]
Yes, this is a limitation of the current CLI. These are the supported file extensions:

sql,prc,fnc,pks,pkb,trg,vw,tps,tpb,tbp,plb,pls,rcv,spc,typ,aqt,aqp,ctx,dbl,tab,dim,snp,con,collt,seq,syn,grt,sp,spb,sps,pck,SQL,PRC,FNC,PKS,PKB,TRG,VW,TPS,TPB,TBP,PLB,PLS,RCV,SPC,TYP,AQT,AQP,CTX,DBL,TAB,DIM,SNP,CON,COLLT,SEQ,SYN,GRT,SP,SPB,SPS,PCK

You can reduce the list with the filter parameter but you cannot extend it. It's an open enhancement for a future release (internal ticket number is PLSQLCOP-246, we have to replace the Eclipse based file association with an own mechanism). For commercial licensees we extend the list on request.

For the time being you have to rename the file extension to process it with the PL/SQL Cop CLI.

**Comment by kkhan1008** [comment]
Thank you for the clarification.
